builds:
  - 
    main: rpg.go
    binary: rpg

archives:
  -
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ if eq .Arch "386" }}i386{{ else }}{{ .Arch }}{{ end }}'
    format_overrides:
      - goos: windows
        format: zip
    files:
      - 
