builds:
  - 
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - "386"
      - "amd64"
    main: rpg.go
    binary: rpg

archives:
  -
    format_overrides:
      - goos: windows
        format: zip
