builds:
  - 
    main: rpg.go
    binary: rpg

archives:
  -
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch | replace '386' 'i386' }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - rpg
      - rpg.exe
